apiVersion: apps/v1
kind: Deployment
metadata:
  name:  aplikasi-nginx
  namespace: default
  labels:
    app:  aplikasi-nginx
spec:
  selector:
    matchLabels:
      app: aplikasi-nginx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  aplikasi-nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  aplikasi-nginx
        image:  nginx
        env:
        - name:  database_port
          value: "3306"
        - name:  database_username  
          value: databasetest
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-config-ku
              key: password_db


---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config-ku
type: Opaque
data:
  password_db: MTIzNDU2
  # Example:
  # password: {{ .Values.password | b64enc }}

# melihat env didalam pod
#kubectl exec -it {pod} -- env

