apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: web
          containerPort:  80
          
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - port:  8080
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name:  curl
  labels:
    name:  curl
spec:
  containers:
      - name:  curl
        image:  khannedy/nginx-curl