apiVersion: apps/v1
kind: Statefulset
metadata:
  name:  nginx-headless
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-headless
  replicas: 3
  template:
    metadata:
      labels:
        app:  nginx-headless
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx-headless
        image:  nginx:alpine
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: nginx-headless
  ports:
  - port: 80
    targetPort: 80


